version: '3.5'

services:
  bitter:
    image: ${DOCKER_PATH}/api:${APP_VERSION}
    container_name: ${APP_HOST}
    restart: always
    build: .
    ports:
      - '${APP_PORT}:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=$APP_ENVIRONMENT
      - DATAACCESS__CONNECTIONSTRING=$CONNECTION_STRING
      - DATAACCESS__DATABASENAME=$DATABASE_NAME
      - TELEGRAM__BOTTOKEN=$BOT_TOKEN
      - PASSWORDS__Admin=$ADMIN_PASSWORD
    networks:
      - nginx

networks:
  nginx:
    external:
      name: nginx